# Generated by Django 4.2.13 on 2025-08-25 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création automatique', verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification automatique', verbose_name='Modifié le')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant UUID non-modifiable', unique=True, verbose_name='Identifiant unique')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modification')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver au lieu de supprimer', verbose_name='Actif')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Désactivé le')),
                ('site_name', models.CharField(default='SmartQueue Sénégal', max_length=100, verbose_name='Nom du site')),
                ('site_description', models.TextField(blank=True, verbose_name='Description du site')),
                ('support_email', models.EmailField(default='support@smartqueue.sn', max_length=254, verbose_name='Email support')),
                ('support_phone', models.CharField(default='+221338000000', max_length=13, verbose_name='Téléphone support')),
                ('default_ticket_expiry_minutes', models.PositiveIntegerField(default=30, verbose_name='Expiration ticket par défaut (min)')),
                ('default_appointment_duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée RDV par défaut (min)')),
                ('max_tickets_per_user_per_day', models.PositiveIntegerField(default=5, verbose_name='Max tickets/utilisateur/jour')),
                ('max_appointments_per_user_per_day', models.PositiveIntegerField(default=3, verbose_name='Max RDV/utilisateur/jour')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='SMS activés')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push activés')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Emails activés')),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Désactive temporairement l'application", verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Message de maintenance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated', to=settings.AUTH_USER_MODEL, verbose_name='Désactivé par')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création automatique', verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification automatique', verbose_name='Modifié le')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('download', 'Téléchargement'), ('upload', 'Upload'), ('payment', 'Paiement'), ('notification', 'Notification'), ('api_call', 'Appel API'), ('error', 'Erreur')], max_length=20, verbose_name="Type d'action")),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modèle concerné')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID objet')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires JSON', verbose_name='Métadonnées')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': 'Journal des activités',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_activi_user_id_599332_idx'), models.Index(fields=['action_type', 'created_at'], name='core_activi_action__e16858_idx'), models.Index(fields=['model_name', 'object_id'], name='core_activi_model_n_1c017b_idx')],
            },
        ),
    ]
