# Generated by Django 4.2.13 on 2025-08-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='business_se_organiz_c9ec9a_idx',
            old_name='services_se_organiz_63d08e_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='business_se_categor_95f642_idx',
            old_name='services_se_categor_e29361_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='business_se_require_bf24f0_idx',
            old_name='services_se_require_0540d4_idx',
        ),
    ]
