# Generated by Django 4.2.13 on 2025-09-17 11:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_services_se_organiz_63d08e_idx_business_se_organiz_c9ec9a_idx_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement (B2C)', 'verbose_name_plural': 'Paiements (B2C)'},
        ),
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'verbose_name': 'Plan de tarification (B2B)', 'verbose_name_plural': 'Plans de tarification (B2B)'},
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='appointment_fee',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='max_appointments_per_month',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='no_show_penalty',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='ticket_fee',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Frais annuels (CFA)'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='fee_per_sms',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais par SMS (CFA)'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='fee_per_ticket',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais par ticket (CFA)'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='max_sms_per_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max SMS/mois'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frais mensuels (CFA)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ticket_fee', 'Frais de ticket'), ('appointment_fee', 'Frais de RDV'), ('service_fee', 'Frais de service'), ('penalty_fee', 'Pénalité (no-show)'), ('other', 'Autre')], default='service_fee', max_length=20, verbose_name='Type de paiement'),
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro de facture')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (CFA)')),
                ('status', models.CharField(choices=[('due', 'À payer'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='due', max_length=20, verbose_name='Statut')),
                ('billing_period_start', models.DateField(verbose_name='Début de période')),
                ('billing_period_end', models.DateField(verbose_name='Fin de période')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='business.organization', verbose_name='Organisation facturée')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentplan', verbose_name='Plan facturé')),
            ],
            options={
                'verbose_name': "Facture d'abonnement (B2B)",
                'verbose_name_plural': "Factures d'abonnement (B2B)",
                'ordering': ['-due_date'],
            },
        ),
    ]
