# Generated by Django 4.2.13 on 2025-09-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_alter_paymentplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to='payments.subscriptioninvoice', verbose_name="Facture d'abonnement liée"),
        ),
    ]
