# Generated by Django 4.2.13 on 2025-08-19 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('appointment_number', models.CharField(editable=False, help_text='Généré automatiquement (ex: RDV001)', max_length=20, unique=True, verbose_name='Numéro de RDV')),
                ('scheduled_date', models.DateField(help_text='Date prévue du rendez-vous', verbose_name='Date du RDV')),
                ('scheduled_time', models.TimeField(help_text='Heure prévue du rendez-vous', verbose_name='Heure du RDV')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('rescheduled', 'Reporté'), ('checked_in', 'Arrivé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('no_show', 'Absent')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Normale'), ('medium', 'Importante'), ('high', 'Urgente')], default='low', max_length=10, verbose_name='Priorité')),
                ('customer_notes', models.TextField(blank=True, help_text='Raison du RDV, besoins spéciaux, etc.', verbose_name='Notes du client')),
                ('customer_phone', models.CharField(blank=True, help_text='Au cas où différent du compte', max_length=15, verbose_name='Téléphone de contact')),
                ('staff_notes', models.TextField(blank=True, help_text='Notes pour le personnel', verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Commencé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Rappel envoyé le')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Confirmation envoyée')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='0=Lundi, 6=Dimanche', verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(help_text='Format: 09:00', verbose_name='Heure de début')),
                ('end_time', models.TimeField(help_text='Format: 17:00', verbose_name='Heure de fin')),
                ('slot_duration', models.IntegerField(default=30, help_text='Durée en minutes (15-120 min)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Durée du créneau (minutes)')),
                ('max_appointments', models.IntegerField(default=1, help_text='Combien de personnes maximum par créneau', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre max de RDV par créneau')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='organizations.organization', verbose_name='Organisation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Créneau de RDV',
                'verbose_name_plural': 'Créneaux de RDV',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('organization', 'service', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='created, confirmed, cancelled, rescheduled, etc.', max_length=50, verbose_name='Action')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appointments.appointment', verbose_name='Rendez-vous')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Historique RDV',
                'verbose_name_plural': 'Historique RDV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.appointmentslot', verbose_name='Créneau'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Personnel assigné'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='Service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'status'], name='appointment_custome_6b9467_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'scheduled_date'], name='appointment_organiz_768c45_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service', 'scheduled_date'], name='appointment_service_97f837_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_date'], name='appointment_status_93b56b_idx'),
        ),
    ]
