# Generated by Django 4.2.13 on 2025-08-14 20:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Nom commercial')),
                ('type', models.CharField(choices=[('bank', 'Banque'), ('hospital', 'Hôpital/Clinique'), ('government', 'Administration publique'), ('telecom', 'Télécommunication'), ('insurance', 'Assurance'), ('business', 'Entreprise privée'), ('education', 'Établissement éducatif'), ('retail', 'Commerce/Retail'), ('other', 'Autre')], max_length=20, verbose_name="Type d'organisation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'immatriculation")),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format: +221XXXXXXXXX', regex='^\\+221[0-9]{9}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email principal')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint-louis', 'Saint-Louis'), ('diourbel', 'Diourbel'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kaolack', 'Kaolack'), ('kaffrine', 'Kaffrine'), ('tambacounda', 'Tambacounda'), ('kedougou', 'Kédougou'), ('kolda', 'Kolda'), ('sedhiou', 'Sédhiou'), ('ziguinchor', 'Ziguinchor'), ('matam', 'Matam')], max_length=20, verbose_name='Région')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('subscription_plan', models.CharField(choices=[('starter', 'Pack Starter'), ('business', 'Pack Business'), ('enterprise', 'Pack Enterprise'), ('custom', 'Pack Sur Mesure')], default='starter', max_length=20, verbose_name="Plan d'abonnement")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('trial', "Version d'essai")], default='trial', max_length=20, verbose_name='Statut')),
                ('subscription_start_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('max_counters', models.PositiveIntegerField(default=3, verbose_name='Max guichets')),
                ('max_staff_users', models.PositiveIntegerField(default=5, verbose_name='Max employés')),
                ('timezone', models.CharField(default='Africa/Dakar', max_length=50)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('default_language', models.CharField(default='fr', max_length=5)),
                ('notifications_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organizations_organization',
            },
        ),
    ]
